version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - config.env
    depends_on:
      postgres:
        condition: service_healthy
      
    volumes:
      - .:/app
    networks:
      - graphnet

  
  postgres: 
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    networks:
      - graphnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"] # Check both user AND db
      interval: 5s
      timeout: 5s
      retries: 5
    

volumes:
  pg_data: 

networks:
  graphnet:
    driver: bridge